### PR TITLE
Feat/login screen

### PR DESCRIPTION
**Pull request by Jrod7938**
This pull request closes issues #30 #29 #28 #27 #26 #25.

Video Demonstration of User Account Creation:
https://github.com/Jrod7938/TxTchangeApp/assets/46418742/c0a6fabc-ae87-4f1a-a5e5-bc1371c6f428

Video Demonstration of User Already Logged In:
https://github.com/Jrod7938/TxTchangeApp/assets/46418742/07ad2054-9d24-4a86-a344-99cfbdd79443

Video Demonstration of The Database reaction to an account being created:
https://github.com/Jrod7938/TxTchangeApp/assets/46418742/00c9e06b-c08e-4124-ba44-941dd70fc463

### CODE REVIEW

**Comment by Jrod7938** [comment]
Excuse the spam but I was updating the GitHub actions to automatically run our android UI tests when we submit a pull request. All actions have passed for this pull request. 

Checks are:
- check if user can login with valid credentials
- check if the user can create an account with valid credentials
- check if the login button is disabled when the Email is wrong and the password is less than 6 characters
- check if the create account button is disabled when the email is wrong and the password is less than 6 characters
- Check if email input field is rendered
- Check if password field is rendered
- check if login button is rendered 
- check if Create account button is rendered
- check if sign up button is rendered
- check if login (Button next to Have an account?) is rendered

**Comment by Jrod7938** [comment]
Video of Tests Running and Completing:
https://github.com/Jrod7938/TxTchangeApp/assets/46418742/50cedc04-9def-47e2-a08c-c0ec717a1440

**Comment by Jrod7938** [comment]
All bugs have been fixed and all tests have passed

**Comment by Jrod7938** [comment]
Bugs #33 #34 have been fixed, merging this pull request will successfully close them.

**Comment by Jrod7938** [comment]
Tests:
https://github.com/Jrod7938/TxTchangeApp/assets/46418742/794af342-6c39-4904-9bba-5fa6fd8efcdc

**Review by Holesum — APPROVED** [review]

**Pull request merged**
