### PR TITLE
Update/HomeScreen+SearchScreen

### PR DESCRIPTION
**Pull request by Jrod7938**
Video Demo of Screen Updates
https://github.com/Jrod7938/TxTchangeApp/assets/46418742/1b7bd42a-0275-4519-8593-0515d24c5ee4

### CODE REVIEW

**Comment by Jrod7938** [comment]
This pull request officially closes #70 #58

**Comment by jesma14** [comment]
I like this new design. It's very clean and uniform.

**Comment by jesma14** [comment]
Not sure how possible this is, but being that the category search takes you to the search page, users who aren't familiar w the app wouldn't know to click it again to activate the search bar. Maybe instead of clicking the nav icon twice, you can have a button on the top of the screen that says something like " < Back to Search" which will show the full search component

**Comment by Jrod7938** [comment]
Demo of navigating to search from category search
https://github.com/Jrod7938/TxTchangeApp/assets/46418742/0d53ab9f-826e-41f5-8b69-dab4b290316c

**Review by jesma14 — APPROVED** [review]
👍

**Pull request merged**
