### PR TITLE
Feat/bottom app navigation

### LINKED ISSUE #54: U6: Create a navigation overlay
Referencing the UI mocks and using Android Studio, assemble a component that overlays all screens with links to main pages

### PR DESCRIPTION
**Pull request by Jrod7938**
Added a navigation bar overlay for the screens, this pull request closes #54 #57  : 
https://github.com/Jrod7938/TxTchangeApp/assets/46418742/b2831205-ebee-4c73-b34d-b1edfd5eb72b

### CODE REVIEW

**Comment by jesma14** [comment]
Hey, can you include images of the bottom navigation in this pull request?

**Comment by Jrod7938** [comment]
> Hey, can you include images of the bottom navigation in this pull request?

I have also pinned a video to the top comment^
Screenshot 2023-10-22 at 4 54 07 PM

**Comment by jesma14** [comment]
Hey, do you think you can maybe format it to look something like this (just the bottom, but when you do the top it would work the same way)? Also, I don't think there is enough color contrast between clicked and unclicked icons. The colors looks too similar. 

NavBar

**Comment by Jrod7938** [comment]
> Hey, do you think you can maybe format it to look something like this (just the bottom, but when you do the top it would work the same way)? Also, I don't think there is enough color contrast between clicked and unclicked icons. The colors looks too similar.
> 
> NavBar


Updated app icons: 
https://github.com/Jrod7938/TxTchangeApp/assets/46418742/bf0095c8-96c8-4eec-92e7-5568dc861f79

**Comment by jesma14** [comment]
Great I think this looks really good. Last few things, I see that there is a line above the navigation bar in light mode. Could you do the same in dark mode? Also, for the dark mode color, it's good that there is more contrast but maybe can we make the unclicked icons (light grey) a bit darker (or closer to white)? We want enough contrast between the icon states, but also easy to see against the background. It's a little challenging to see against the black.  Thanks :)

**Comment by Jrod7938** [comment]
> Great I think this looks really good. Last few things, I see that there is a line above the navigation bar in light mode. Could you do the same in dark mode? Also, for the dark mode color, it's good that there is more contrast but maybe can we make the unclicked icons (light grey) a bit darker (or closer to white)? We want enough contrast between the icon states, but also easy to see against the background. It's a little challenging to see against the black. Thanks :)

Im using the material theme, if you wish to update the colors; open a pull request and update the material theme. Below is the icons with the provided material them colors: 

https://github.com/Jrod7938/TxTchangeApp/assets/46418742/e4ee96a1-09d8-47d4-8ca9-75f6c0ba3528

**Comment by jesma14** [comment]
Okay, the blue looks good. And if this is the theme of the UI we can work with this. Good to go

**Review by jesma14 — APPROVED** [review]
Everything looks good here.

**Pull request merged**
